# Full redeploy-only pipeline for dockerized k8s service with in-repo helm file. 
# Stage templates are pulled from NexTech-AR-Solutions/pipeline repo
# Stages: 
## - Setup Stage: Set docker image tag, save changelog artifact
## - Deploy Stage: Deploy using in-repo helm chart to ado environment
## - Cleanup Stage: purge unused acr images 

## Triggers
trigger:
  branches:
    include: 
     - DEVOPS_AUTO
  paths:
    include: 
     - helm/values/dev-nln-vip.yaml
    exclude: 
     - /

pr: none 

## Extend variables template
variables: 
  - template: variables.yml

## External resources
resources:  
  repositories:
    - repository: self
    - repository: pipeline
      type: github 
      endpoint: NexTech-AR-Solutions
      name: NexTech-AR-Solutions/pipeline
      refs: $(pipelineRef)

# Pool defaults to 'ubuntu-latest'
pool: 
  vmImage: $(vmImageName)

stages:
   - template: templates/stages/redeploySetup.yaml@pipeline
   - template: templates/stages/skipBuild.yaml@pipeline
   - template: templates/stages/helmDeploy.yaml@pipeline
   - template: templates/stages/cleanup.yaml@pipeline
